export const HOME = {
  meta: {
    title: "Trang chủ EVstep",
    desc: "Evstep - luyện thi tiếng anh",
  },
};

export const CHUNG_CHI_A2 = {
  meta: {
    title: "Chứng chỉ tiếng Anh A2",
    desc: "Thông tin chi tiết chứng chỉ tiếng Anh A2",
  },
};

export const CHUNG_CHI_B1 = {
  meta: {
    title: "Chứng chỉ tiếng Anh B1",
    desc: "Thông tin chi tiết chứng chỉ tiếng Anh B1",
  },
};

export const KHUNG_NL = {
  meta: {
    title: "Khung năng lực bậc 6",
    desc: "Thông tin chi tiết khung năng lực",
  },
};

export const LICH_KHAI_GIANG = {
  meta: {
    title: "Lịch khai giảng evstep",
    desc: "Thông tin chi tiết lịch khai giảng evstep",
  },
};

export const LICH_THI = {
  meta: {
    title: "Lịch thi evstep",
    desc: "Thông tin chi tiết lịch thi evstep",
  },
};

export const TIN_TUC = {
  meta: {
    title: "Tin tức",
    desc: "Tin tức về Evstep",
  },
};

export const BASE_URL_MEDIAS =
  "http://localhost/wordpress/wp-content/uploads/2023/08";
